// Automatically generated by swiftrsrc. Do not edit.

struct ImagesCatalog {
	struct BookDetail {
		static var AudioWave: UIImage { return UIImage(named: "AudioWave")! }
		static var Equalizer1: UIImage { return UIImage(named: "Equalizer1")! }
		static var Equalizer2: UIImage { return UIImage(named: "Equalizer2")! }
		static var Equalizer3: UIImage { return UIImage(named: "Equalizer3")! }
		static var Error: UIImage { return UIImage(named: "Error")! }
		static var FastForward: UIImage { return UIImage(named: "FastForward")! }
		static var FastForwardFilled: UIImage { return UIImage(named: "FastForwardFilled")! }
		static var Pause: UIImage { return UIImage(named: "Pause")! }
		static var PauseFilled: UIImage { return UIImage(named: "PauseFilled")! }
		static var Play: UIImage { return UIImage(named: "Play")! }
		static var PlayFilled: UIImage { return UIImage(named: "PlayFilled")! }
		static var Rewind: UIImage { return UIImage(named: "Rewind")! }
		static var RewindFilled: UIImage { return UIImage(named: "RewindFilled")! }
		static var Update: UIImage { return UIImage(named: "Update")! }
		static var Upload: UIImage { return UIImage(named: "Upload")! }
	}
	struct Organizational {
		static var Bug: UIImage { return UIImage(named: "Bug")! }
	}
	struct UserInterface {
		static var Checkmark: UIImage { return UIImage(named: "Checkmark")! }
		static var Forward: UIImage { return UIImage(named: "Forward")! }
	}
}

