// Automatically generated by swiftrsrc. Do not edit.

struct MainStoryboard {
	struct StoryboardIdentifiers {
		static let TBNavigationViewController = "TBNavigationViewController"
		static let TBDashboardViewController = "TBDashboardViewController"
		static let TBInformationViewController = "TBInformationViewController"
		static let TBLanguageTableViewController = "TBLanguageTableViewController"
		static let TBBookTableViewController = "TBBookTableViewController"
		static let TBBookDetailViewController = "TBBookDetailViewController"
	}
	struct ReuseIdentifiers {
		static let InformationCellIdentifier = "InformationCellIdentifier"
		static let LanguageCellIdentifier = "LanguageCellIdentifier"
		static let BookCellIdentifier = "BookCellIdentifier"
		static let ChapterCellIdentifier = "ChapterCellIdentifier"
	}
	struct SegueIdentifiers {
		static let ShowLanguagesIdentifier = "ShowLanguagesIdentifier"
		static let ShowBooksIdentifier = "ShowBooksIdentifier"
		static let ShowInformationIdentifier = "ShowInformationIdentifier"
		static let ShowArticleIdentifier = "ShowArticleIdentifier"
		static let ShowBookIdentifier = "ShowBookIdentifier"
	}
}
